apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-webapp-deployment
  labels:
    app: users-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: users-webapp
        tier: frontend
    spec:
      containers:
      - name: users-webapp
        image: oscarsaavedra12/usuariosapp:latest
        ports:
        - containerPort: 80