on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
name: CI/CD Pipeline

jobs:
  pre-build:
    name: Pre build steps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      #- run: npm run test:ci
      - run: sudo npm run build
        
  build:
    name: Build and Push DH
    runs-on: ubuntu-latest
    needs: pre-build
    
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build docker image
        run: docker build . --file Dockerfile --tag oscarsaavedra12/usuariosapp:latest
      - name: docker hub push
        run: docker push ${{secrets.DOCKER_USER}}/usuariosapp
      
  deploy:
    name: Deploy in kubernetes cluster
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: DigitalOcean kubeconfig credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 f74e3210-45c3-4484-8bd6-bb177dc2d973
      - name: Create deploy
        run: kubectl apply -f $GITHUB_WORKSPACE/deploy.yml
      - name: Create service
        run: kubectl apply -f $GITHUB_WORKSPACE/service.yml
